import { IsNotEmpty, IsString, IsOptional, IsBoolean } from 'class-validator';

export class CreateJobDto {
  @IsNotEmpty()
  @IsString()
  title: string;

  @IsNotEmpty()
  @IsString()
  description: string;

  @IsNotEmpty()
  @IsString()
  location: string;

  @IsOptional()
  @IsBoolean()
  autoGenerateDescription?: boolean;
} 